### PR TITLE
Updated range.py 

### PR DESCRIPTION
**Pull request by L-crypt**
### 1. This pull request resolves #???
#24 

### 2. Description
updated range.py
Added the challenge as well for the tutorial 

### 3. Fill in checklist by marking [x]

- [x] I've read the CONTRIBUTING.md
- [x] I was assigned to this issue
- [x] My code is formatted using required linting
- [x] I've run my code locally and checked it works

### CODE REVIEW

**Comment by funbeedev** [comment]
@L-crypt Please also add in a challenge to the tutorial.

**Comment by L-crypt** [comment]
ok I will do add the challenge

**Comment by L-crypt** [comment]
I have updated the challenge. Please do give it a check.

**Comment by L-crypt** [comment]
I accidentally commit new changes in the same branch only

**Comment by funbeedev** [comment]
@L-crypt Is the challenge added in completely for range.py? I wasn't sure what this challenge meant:
```
# Lets give a challenge to try out what we learnt:
# Like what we need to do is compute sum of first n natural numbers by using the range function and not the formula.
```
Also please include the challenge in the area provided which is in this part of the file:
```
# ------------------------------------------------------------------------------------
# Challenge: list challenges to be completed here. minimum of one challenge per tutorial
# ------------------------------------------------------------------------------------
```

**Comment by L-crypt** [comment]
I have updated with the challenge . I hope the language is enough clear.

**Comment by funbeedev** [comment]
@L-crypt I have a few queries.

In your challenge:
```
# ------------------------------------------------------------------------------------
# Challenge: Take user based input n and then compute the sum of first n natural numbers and print the sum.
# ------------------------------------------------------------------------------------
```
By natural numbers do you just mean 1,2,3,4,5... etc?

Also could you add an example showing range used in loops. Might help the reader better understand the uses of the range function.
Thanks!

**Comment by L-crypt** [comment]
Yes by natural numbers I meant (1,2,3...,n). As you suggested I have mentioned it in the tutorial as well. Added some examples as well to help our students understand stuff more easily. Please look and ask for any more requirements for the tutorial and give a check for my other PR as well for updating #43 [ using-continue.py ] . Also can you please ensure to consider this so that I can be a part of Hacktoberfest successfully. Thanks in advance :)

**Comment by L-crypt** [comment]
Pleased to Help @funbeedev

**Comment by funbeedev** [comment]
@L-crypt Thanks for making those changes, looks good now!

**Comment by L-crypt** [comment]
@funbeedev pls tell me what is the meaning of ineligible repository showing on my hacktoberfest profile because now my count is getting reduced due to this. Pls tell me what it means so that I can take care of  it next time.

**Comment by L-crypt** [comment]
Ineligible repo is showing in all of my PRs : #38 , #42 , #43 
I am concerned , pls kindly tell me the reason.

**Comment by funbeedev** [comment]
@L-crypt 
You did nothing wrong!
Unfortunately this looks to be a bug with the hacktoberfest system that's affecting PRs that were still under review after hacktoberfest ended. I've contacted the organisers of hacktoberfest about this and they acknowledge its a flaw in their logic but they don't seem to be willing to fix it. I'm still waiting to see if it will be fixed.
It may help if you report the problem at their email: hacktoberfest@digitalocean.com and maybe they will do something about it if more people say its affecting them.

**Comment by L-crypt** [comment]
Ok , So that's a bug . I have reported but can you pls declare an announcement about reporting the problem. So, that we can gather more audience to support for the cause @funbeedev .

**Comment by funbeedev** [comment]
@L-crypt sure I'll make an announcement so more people can get in touch with hacktoberfest :)

**Comment by L-crypt** [comment]
@funbeedev good to know :)

**Comment by funbeedev** [comment]
@L-crypt  I've announced it in the issues section now 👍🏿

**Comment by L-crypt** [comment]
@funbeedev till now the condition is showing ineligible repo but the issue #64 is accepted. What should I do now ?

**Comment by funbeedev** [comment]
@L-crypt Unfortunately its a problem with Hacktoberfest so there's not much we can do.. I don't know if they will fix it :( I was affected also by this problem :(

**Comment by L-crypt** [comment]
@funbeedev thanks for the support :)
I also wanted to ask like if there is any ongoing or incoming open source competition like hacktoberfest , so that I can try and practice more.
Can u suggest some??

**Comment by L-crypt** [comment]
Or any remote internships I can apply for a change.
Thanks in advance :)

**Comment by funbeedev** [comment]
@L-crypt 
Hi,
I'm aware of this competition that's kind of similar to hacktoberfest: https://itch.io/jam/game-off-2020
In that one you have to submit a game you made yourself before December 1st.

I'm not familiar with remote internships unfortunately... But maybe you can get involved with a developer community?
https://dev.to/ is a nice community!

You can also practice more by searching for open source projects here on Github. If you see any that interests you make a contribution. It's a great way to learn :)

**Comment by L-crypt** [comment]
Actually I was interested in knowing more about you.
Like apart from the open source mentor what exactly are you pursuing.
Can you brief about it. :)

**Comment by funbeedev** [comment]
@L-crypt 
I work as an Embedded programmer but I'm exploring open source and GitHub in my free time! 
My goal right now is to setup a developer community that encourages people to code more by working on open source projects here on GitHub.

What's your background and goals??

**Comment by L-crypt** [comment]
I am a beginner a CS student 
Exploring open source we can say.
Also some competitive coding :)

**Pull request merged**
