### PR TITLE
Update List-declartion

### LINKED ISSUE #14: declaring-lists python tutorial
Populate lists/declaring-lists.py with a tutorial and challenge.

### PR DESCRIPTION
**Pull request by ashutosh007865**
briefly describe the about list and its functions as well, and also add one challenge

### 1. This pull request resolves #14 
(^Fill in the issue number after #)

### 2. Description
(Briefly describes the list and its component)

### 3. Fill in the checklist by marking [x]

- [x] I've read the CONTRIBUTING.md
- [x] I was assigned to this issue
- [x] My code is formatted using required linting
- [x] I've run my code locally and checked it works

### CODE REVIEW

**Comment by funbeedev** [comment]
@ashutosh007865 There's still a few things that need to be changed:

1. The python file is not executing, please fix. The following error occurs when running the file:
```
Traceback (most recent call last):
1
  File "lists/declaring-lists.py", line 22, in <module>
    lst.sort()   # this will arrange the element in the ascending order.
TypeError: '<' not supported between instances of 'list' and 'int'
hello
```

2. The challenge needs more detail. I'm not sure what the challenge is asking for.

Also note there is no need to make another PR. Please update this PR with the requested changes. Thanks!

**Comment by funbeedev** [comment]
@ashutosh007865 I see you've made changes. However the challenge still needs more description. What should the learner try to do using lists? 
Its this part that needs editing:
```
# Challenge: list challenges to be completed here. minimum of one challenge per tutorial
# 1. take input from the user into the list
# ------------------------------------------------------------------------------------
# 
```

**Comment by ashutosh007865** [comment]
Okay I will brief the challenge

**Comment by funbeedev** [comment]
@ashutosh007865 Thanks for editing 👍🏿

**Comment by ashutosh007865** [comment]
Thanks for your support🙏🙏

**Pull request merged**
