### PR TITLE
Populate if-else

### LINKED ISSUE #22: if-else python tutorial
Populate conditions/if-else.py with a tutorial and challenge.

### PR DESCRIPTION
**Pull request by JorgeMadson**
### 2. Description
Teaching if, else, elif

### 3. Fill in checklist by marking [x]

- [x] I've read the CONTRIBUTING.md
- [x] I was assigned to this issue
- [x] My code is formatted using required linting
- [x] I've run my code locally and checked it works

### CODE REVIEW

**Comment by funbeedev** [comment]
@JorgeMadson Thanks for the PR. 

Note the python file should be executable. If the code in the challenge is not executable, add it as a comment. Then mention in the challenge to uncomment the code. 
Please edit the PR, thanks.

**Comment by JorgeMadson** [comment]
Btw nice CI.
Ok, I have fixed sorry for the delay.

**Comment by funbeedev** [comment]
@JorgeMadson thanks for the revision, looks good.
FYI I made a slight edit in challenge description. changed 'replace_this' to replace_me' on line 26 to match the challenge code.

**Comment by JorgeMadson** [comment]
Ok, thank @funbeedev !

**Pull request merged**
