### PR TITLE
Added code to reading-files

### LINKED ISSUE #19: reading-files python tutorial
Populate file-handling/reading-files.py with a tutorial and challenge.

### PR DESCRIPTION
**Pull request by raghuchandan1**
### 2. Description
Added code to the file reading-files to read a file and display the contents

### 3. Fill in checklist by marking [x]

- [x] I've read the CONTRIBUTING.md
- [x] I was assigned to this issue
- [x] My code is formatted using required linting
- [x] I've run my code locally and checked it works

### CODE REVIEW

**Comment by raghuchandan1** [comment]
@funbeedev Please check my PR

**Comment by raghuchandan1** [comment]
Sorry I have added the integers file to this PR by mistake I am issuing another commit which reverts the changes

**Comment by raghuchandan1** [comment]
@funbeedev Review the changes to the reading-files.py file

**Comment by raghuchandan1** [comment]
I am opening a new PR with fewer commits. This PR has become clumsy

**Comment by funbeedev** [comment]
replaced by PR #69

**Pull request closed without merging**
