### PR TITLE
feat(tuple): Create tuple-basics.py under tuples directory

### LINKED ISSUE #91: [tutorial] tuple
**Description of the tutorial**
- Definition of `tuple`
- Mutability vs immutability (Compared to `list`)
- Tuple packing

**Do you want to be assigned to work on this?**
(mark [x])
- [x] YES
- [ ] NO

**Optional: Any additional info you want to add**

### PR DESCRIPTION
**Pull request by nayeonshin**
### 2. Description
- Created `tuples` dir and `tuples-basic.py` under `tuples`
- Covered how to declare and get the length of a tuple; tuple unpacking

### 3. Fill in checklist by marking [x]

- [x] I've read the CONTRIBUTING.md
- [x] I was assigned to this issue
- [x] My code is formatted using required linting --> Used Black
- [x] I've run my code locally and checked it works

Apologies for my late submission!
I didn't want to touch the README, so I guess it should be updated after this PR gets merged.

### CODE REVIEW

**Comment by nayeonshin** [comment]
@funbeedev Hey! Could you please take a look into this PR? I'm not sure why some checks are failing.

**Comment by funbeedev** [comment]
@nayeonshin Could you please update your PR so only `tuples-basic.py` is the only file submitted? I've marked this PR as hacktoberfest accepted  so it counts in time for hacktoberfest but make the changes needed so we can merge into the repo. Thanks!

**Comment by nayeonshin** [comment]
@funbeedev Yes, of course! TYSM :) Doing this rn

**Comment by nayeonshin** [comment]
Hmm... this is weird. I might have messed something up in `run-modified-python.sh`. Don't recall if I directly changed this when working in this PR for the first time. I just tried manually fixing it (by putting the same thing from the upstream's main branch), but it doesn't seem to be successful. Sorry about the hassle! 😔

**Comment by funbeedev** [comment]
@nayeonshin hmm not sure why that's happening. Are you able to revert the changes to `run-modified-python.sh` file on your git repo locally? If that doesn't work you can raise another PR

**Comment by nayeonshin** [comment]
@funbeedev Thanks for your reply! I succeeded in reverting that file but the `execute-modified-python-file` still fails 🤯:
```
Run echo "job: running script to execute modified file:"
job: running script to execute modified file:
run-sh: Inside run-modified-python.sh
run-sh: Content of files_modified.json: [
    ".github/workflows/run-modified-python.sh",
    "tuples/tuples-basic.py"
]
run-sh: After parsing, file to execute: 
.github/workflows/run-modified-python.sh
tuples/tuples-basic.py
run-sh: This is a .py file, executing
  File ".github/workflows/run-modified-python.sh", line 3
    echo "run-sh: Inside run-modified-python.sh"
         ^
SyntaxError: invalid syntax
Error: Process completed with exit code 1.
```

**Comment by nayeonshin** [comment]
@funbeedev Hey there! Could you please help me resolve this? TY in advance :)

**Comment by funbeedev** [comment]
@nayeonshin Sorry for the delay in checking this and thanks for the reminder!
I can't see why the check is failing and it appears to be an issue with the workflow run. I'll merge your PR and sort out the workflow issue separately. Thanks for your contribution! :smile: :tada:

**Pull request merged**
