### PR TITLE
Update commenting.py

### LINKED ISSUE #16: commenting in python tutorial
Populate getting-started/commenting.py with a tutorial and challenge.

### PR DESCRIPTION
**Pull request by S10MC2015**
fixes #16

### CODE REVIEW

**Comment by funbeedev** [comment]
@S10MC2015 Can you edit the challenge to something that requires commenting out existing code?

**Comment by S10MC2015** [comment]
> @S10MC2015 Can you edit the challenge to something that requires commenting out existing code?

so like "1. using comments make this code say "Hello": print("Hello") + ("World") "

or "1. explain what this code does with comments: print("Hello World") "

**Comment by funbeedev** [comment]
> > @S10MC2015 Can you edit the challenge to something that requires commenting out existing code?
> 
> so like "1. using comments make this code say "Hello": print("Hello") + ("World") "
> 
> or "1. explain what this code does with comments: print("Hello World") "

@S10MC2015  Like the first one :)

**Comment by S10MC2015** [comment]
I have changed the line

**Comment by zg888dev** [comment]
@S10MC2015 looks good

**Comment by funbeedev** [comment]
@S10MC2015 thanks

**Pull request merged**
