### PR TITLE
Created tutorial for Dictionary with challenge

### LINKED ISSUE #44: [tutorial] Dictionaries
A basic introduction to declaring, editing and accessing dictionaries and their values.

**Do you want to be assigned to work on this?**
(mark [x])
- [x] YES
- [ ] NO

### PR DESCRIPTION
**Pull request by drentsoft**
### 2. Description
Wrote dictionaries/using_dictionaries.py.
Includes a tutorial covering most basic uses of dictionaries and two challenges, one simple and one more advanced.

### 3. Fill in checklist by marking [x]

- [x] I've read the CONTRIBUTING.md
- [x] I was assigned to this issue
- [x] My code is formatted using required linting
- [x] I've run my code locally and checked it works

### CODE REVIEW

**Comment by funbeedev** [comment]
@drentsoft This has great detail! But is a bit too advanced for a beginner. Can you simply it and remove advanced concepts and challenges? 
Or split into two files "using-dictionaries-basic" and "using-dictionaries-advanced"
thanks!

**Comment by drentsoft** [comment]
Yeah I was worried you might say that. Okay I'll try and split it.

**Comment by funbeedev** [comment]
> Yeah I was worried you might say that. Okay I'll try and split it. Would it be better to do the 2 files as separate PRs?

Two separate PRs would be better!

**Comment by drentsoft** [comment]
Updated pull request with requested changes. Tutorial is shorter and challenge is hopefully much simpler.

**Comment by funbeedev** [comment]
@drentsoft Looks better and teaches the basic very well. Thanks 😃

**Pull request merged**
